module.exports = function() {
return {
	categories: ["html","css","javascript","bootstrap","jquery","xml"],
	html: [	{id:1,
			question:"What does HTML stand for?",
			option:["Hyperlinks and Text Markup Language",
					"Home Tool Markup Language",
					"Hyper Text Markup Language"],
			answer:"Hyper Text Markup Language"},	
			{id:2,
			question:"Who is making the Web standards?",
			option:["The World Wide Web Consortium",
					"Google",
					"Mozilla",
					"Microsoft"],
			answer:"The World Wide Web Consortium"},
			{id:3,
			question:"Choose the correct HTML element for the largest heading:",
			option:["<h6>",
					"<heading>",
					"<h1>",
					"<head>"],
			answer:"<h1>"},
			{id:4,
			question:"What is the correct HTML element for inserting a line break?",
			option:["<break>",
					"<lb>",
					"<br>"],
			answer:"<br>"},
			{id:5,
			question:"What is the correct HTML for adding a background color?",
			option:["<background>yellow</background>",
					"<body bg='yellow'>",
					"<body style='background-color:yellow;'>"],
			answer:"<body style='background-color:yellow;'>"},
			{id:6,
			question:"Choose the correct HTML element to define important text",
			option:["<i>",
					"<b>",
					"<important>",
					"<strong>"],
			answer:"<strong>"},
			{id:7,
			question:"Choose the correct HTML element to define emphasized text",
			option:["<em>",
					"<i>",
					"<italic>"],
			answer:"<em>"},
			{id:8,
			question:"What is the correct HTML for creating a hyperlink?",
			option:["<a url='http://www.w3schools.com'>W3Schools.com</a>",
					"<a href='http://www.w3schools.com'>W3Schools</a>",
					"<a name='http://www.w3schools.com'>W3Schools.com</a>",
					"<a>http://www.w3schools.com</a>"],
			answer:"<a href='http://www.w3schools.com'>W3Schools</a>"},
			{id:9,
			question:"Which character is used to indicate an end tag?",
			option:["^",
					"/",
					"<",
					"*"],
			answer:"/"},
			{id:10,
			question:"How can you open a link in a new tab/browser window?",
			option:["<a href='url' target='new'>",
					"<a href='url' target='_blank'>",
					"<a href='url' new>"],
			answer:"<a href='url' target='_blank'>"},
			],
	css: [	{id:1,
			 question: "What does CSS stand for?",
			 option: ["Computer Style Sheets",
			 		  "Creative Style Sheets",
			 		  "Cascading Style Sheets",
			 		  "Colorful Style Sheets"],
			answer: "Cascading Style Sheets"
			}
		]
	}
}